### ISSUE TITLE
Adding ability to include supporting text

### ISSUE THREAD

**Issue by incrhst** [eea/volto-call-to-action-block#29]
I like this call to action widget. It makes it easier to add a CTA button.
It would be great if it also include supporting text.
For example, I have a use case like this:
![image](https://github.com/eea/volto-call-to-action-block/assets/110049091/76354f69-2bb6-4883-8fc1-c3d40b93fe77)

**Comment by ichim-david** [comment]
@incrhst I don't think this block will ever do this, although you could create a variation where you try to add.

One thing that you could try is a combination of products:
1. https://github.com/eea/volto-columns-block/ - to have columns where you can insert block (2 or 3 columns)
2. https://github.com/eea/volto-block-style/ - to add the background and text style
3. This addon to provide the button
 
Here is an example screenshot:
![column-block](https://github.com/eea/volto-call-to-action-block/assets/152852/afe9298d-783b-43fa-aaf4-075ff847f166)

The bg is full width, the text is not same color but you could achieve your look using custom css.
